### ISSUE TITLE
Architecture's runThreaded threw an error. This should never happen!

### ISSUE THREAD

**Issue by AlchemicRaker** [AlchemicRaker/OpenProlog#10]
```
[17:37:22] [OpenComputers-Computer-1/WARN] [opencomputers]: Architecture's runThreaded threw an error.
This should never happen!
java.util.concurrent.CancellationException: null
        at java.util.concurrent.FutureTask.report(FutureTask.java:121) ~[?:1.8.0_151]
        at java.util.concurrent.FutureTask.get(FutureTask.java:206) ~[?:1.8.0_151]
        at com.syntheticentropy.ocpro.PrologArchitecture.runThreaded(PrologArchitecture.java:127) ~[Pro
logArchitecture.class:?]
        at li.cil.oc.server.machine.Machine.run(Machine.scala:992) [Machine.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThr
eadPoolExecutor.java:180) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPool
Executor.java:293) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151
]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151
]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[17:37:29] [Thread-60/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPoi
nterException
[17:37:29] [Thread-60/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:   at com.syntheti
centropy.ocpro.PrologArchitecture.crash(PrologArchitecture.java:204)
[17:37:29] [Thread-60/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:   at com.syntheti
centropy.ocpro.PrologVM.run(PrologVM.java:37)
```

**Comment by AlchemicRaker** [comment]
Fixed in 0.3.4
